"""ETL — Escuelas Rurales (Pilar Azul · capa 2D de puntos).

Reads ``Escuelas_rurales_CC10mayo.kmz`` (7 Point placemarks), parses the
minimal CDATA payload into a flat 4-field schema (``localidad``, ``ambito``,
``nivel`` + the ``nombre`` from ``<name>``), generates a deterministic slug
per school with collision handling, and emits a single GeoJSON FeatureCollection
consumed by the React frontend:

- ``public/capas/escuelas/escuelas_rurales.geojson``
- ``public/capas/escuelas/escuela-icon.png`` (generated by ``export_icon.py``)

The KMZ extractor is REUSED AS-IS from ``scripts.etl_canales.kmz`` — it
already supports ``Point`` geometry.

No PII leaves the parser: CUE, Departamento, Sector, Directivo, Teléfono,
Email are deliberately IGNORED even though they exist in the CDATA.
"""

__all__: list[str] = []
