"""drop duplicate management indexes

Revision ID: 37d3912d8013
Revises: 7e25b857692b
Create Date: 2026-04-22 14:12:36.225227

The zz_add_management_indexes migration (revision zz_mgmt_indexes) shipped
`idx_*` indexes that duplicate pre-existing `ix_*` indexes on the same
columns. The `ix_*` indexes are auto-generated by SQLAlchemy from
`index=True` in the model definitions and are the ORM-canonical source of
truth. The `idx_*` copies are dead weight on writes and confuse planner
statistics.

Keep the `ix_*`, drop the `idx_*`. The `idx_sugerencias_v2_*` entries are
NOT dropped — sugerencias_v2 has no `ix_*` counterparts, so those three
indexes are genuine and stay.
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "37d3912d8013"
down_revision: Union[str, Sequence[str], None] = "7e25b857692b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop the duplicate idx_* indexes. ix_* counterparts remain."""
    # denuncias — both have ix_denuncias_* equivalents
    op.execute("DROP INDEX IF EXISTS idx_denuncias_created_at")
    op.execute("DROP INDEX IF EXISTS idx_denuncias_estado")

    # reuniones_v2 — both have ix_reuniones_v2_* equivalents
    op.execute("DROP INDEX IF EXISTS idx_reuniones_v2_estado")
    op.execute("DROP INDEX IF EXISTS idx_reuniones_v2_fecha_reunion")

    # tramites_v2 — both have ix_tramites_v2_* equivalents
    op.execute("DROP INDEX IF EXISTS idx_tramites_v2_estado")
    op.execute("DROP INDEX IF EXISTS idx_tramites_v2_tipo")

    # NOTE: idx_sugerencias_v2_{estado,categoria,created_at} are intentionally
    # retained — sugerencias_v2 has no ix_* autogenerated indexes on those
    # columns, so these are NOT duplicates.


def downgrade() -> None:
    """Recreate the dropped idx_* indexes (mirrors zz_mgmt_indexes upgrade)."""
    op.execute("CREATE INDEX IF NOT EXISTS idx_denuncias_estado ON denuncias(estado)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_denuncias_created_at ON denuncias(created_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_tramites_v2_estado ON tramites_v2(estado)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_tramites_v2_tipo ON tramites_v2(tipo)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_reuniones_v2_estado ON reuniones_v2(estado)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_reuniones_v2_fecha_reunion ON reuniones_v2(fecha_reunion)"
    )
