#!/usr/bin/env python3
"""Generate `eval/expected_clasificacion.yaml` from a SHA-pinned corpus checkout.

    python scripts/rag_expected_clasificacion.py \\
        --corpus-path /path/to/consorcio-corpus-legal \\
        --corpus-sha 12043582bf8016288a7e8084e85a4b713a97af2f

**Why a generator and not a hand-written table.** Only 7 of the 35 documents are
derivable from THIS repository — the 6 `es_secundaria` ones and the single
`registro-administrativo` — because `corpus_expectations.yaml` records every
document's `tipo` but no `fuente_url`. The other 28 are decided by the host rule
and can only be settled against the private checkout. A hand-written expectation
for those 28 would be a guess wearing the costume of a fixture.

**What it emits, and what it deliberately does not.** Per document: the id, the
normalized `tipo`, derived `es_secundaria`, the derived class and the evidence
string the rule recorded. No document text, no frontmatter dump, no private
prose. The only URLs that appear are the ones that PROMOTED a document to
`publico` — by construction, the published-gazette URL of a published norm.
`privado` rows carry `es_secundaria` or `sin host en FUENTES_PUBLICAS` and
nothing else, so the artifact cannot leak the provenance of a document the rule
just decided must not travel.

The output is a checked-in expectation from the moment it is committed: CI diffs
the 11 fixture documents against it without a database, and runbook step 8 diffs
all 35 reclassified `rag_documento` rows against it row by row rather than
comparing a single count. Regenerating it is a change-controlled act — the same
owner sign-off `FUENTES_PUBLICAS` and `TIPOS_INSTITUCIONALES` require — because
a regenerated artifact makes any rule change self-consistent and therefore
invisible to the diff that exists to catch it.
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.domains.conocimiento import repository  # noqa: E402
from app.domains.conocimiento.expectations import (  # noqa: E402
    EXPECTED_CLASIFICACION_PATH,
    load_expectations,
)
from app.domains.conocimiento.service import load_corpus, verify_corpus_pin  # noqa: E402

CABECERA = """\
# GENERATED by scripts/rag_expected_clasificacion.py — do not hand-edit.
#
# The expected `clasificacion` of every document at the pinned corpus revision,
# with the evidence string the ingest rule derived it from. Diffed by the unit
# suite (the 11 checked-in fixtures, no database) and by runbook step 8 (all 35
# reclassified rows).
#
# CHANGE CONTROL: editing this file, `FUENTES_PUBLICAS`, `TIPOS_INSTITUCIONALES`,
# `INDICE_NO_PUBLICACION` or `CLASIFICACIONES_ENVIABLES` requires explicit owner
# sign-off recorded in the PR that makes it. Together they ARE the privacy
# boundary in executable form.
#
# `regla_sha256` is a digest over those four artifacts AND over
# `REGLA_MECANICA_VERSION`, the hand-bumped token for how the rule MATCHES —
# host suffix matching and index-URL normalisation — because a digest over
# listed values alone is blind to a rewritten comparison that moves documents
# between classes without touching a single listed value. A rule change that does
# not regenerate this file fails the unit diff — which is exactly the widening
# the 11 fixtures alone cannot see, since 24 documents have no fixture here.
"""


#: Judgment notes carried INTO the artifact, keyed by what they are about.
#: Rendered by the generator so a regeneration cannot quietly drop them — a note
#: that survives only until the next run is not a record.
#:
#: These are notes, not rules. Where a note describes an outcome the owner has
#: not ruled on, the artifact records the class the RATIFIED rule derives and
#: says so; it does not invent a stronger rule to reach a tidier answer.
NOTAS_DE_JUICIO: tuple[tuple[str, str], ...] = (
    (
        "decreto-3780-c-65-obras-cursos-naturales-artificiales",
        "OPEN JUDGMENT, recorded rather than resolved. After the index rule its only "
        "allowlist match is a concrete-document URL on www.cba.gov.ar which is the "
        "publication of a DIFFERENT document (the 2013 SRH norms, which cite this "
        "decree). The ratified rule reads the host of a fuente_url entry; it does not "
        "verify that the URL is the publication of THIS document, so the match stands "
        "and the decree derives `publico`. Requiring the URL to be the document's own "
        "publication would be a NEW rule, stronger than the index rule, and needs its "
        "own ratification — under it this document would fall to `privado`.",
    ),
    (
        "FUENTES_PUBLICAS/aprhi.gob.ar",
        "Inert at this corpus_sha. After the index rule the entry promotes ZERO "
        "documents: every APRHI URL in the corpus is an index or a section landing. "
        "The entry stays because the owner ratified it; this note is the record that "
        "it currently does nothing, so nobody later reads its presence as evidence "
        "that APRHI-published documents are reaching the shippable set.",
    ),
    (
        "INDICE_NO_PUBLICACION",
        "U1's implementation choice for amendment A1's exclusion mechanism: a NAMED "
        "list of exact index URLs present at this SHA, chosen over a heuristic because "
        "every exclusion is then a line a reviewer reads and a diff someone signs off. "
        "A path-shape heuristic would give the same result over these 35 documents and "
        "was not ratified. The cost of the named list — a new index URL at a future "
        "SHA is not excluded until listed — is stated rather than hidden.",
    ),
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus-path", required=True, type=Path)
    parser.add_argument("--corpus-sha", required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=EXPECTED_CLASIFICACION_PATH,
        help="defaults to the checked-in artifact path",
    )
    return parser


def _yaml_str(value: str) -> str:
    """Double-quoted scalar with the two characters YAML actually needs escaped.

    Hand-rolled rather than `yaml.safe_dump`ed for one reason: the file is read
    by humans reviewing a privacy boundary, and the dumper's line-wrapping breaks
    long evidence strings across lines, which makes a URL diff unreadable exactly
    where reading it matters.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render(corpus_sha: str, filas: list[dict[str, object]]) -> str:
    lineas = [
        CABECERA,
        f"corpus_sha: {corpus_sha}",
        f"generado: {datetime.date.today().isoformat()}",
        f"regla_sha256: {repository.regla_clasificacion_sha256()}",
        f"regla_mecanica_version: {repository.REGLA_MECANICA_VERSION}",
        "clasificaciones_enviables:",
    ]
    lineas += [f"  - {clase}" for clase in sorted(repository.CLASIFICACIONES_ENVIABLES)]
    lineas.append("fuentes_publicas:")
    lineas += [f"  - {entrada}" for entrada in repository.FUENTES_PUBLICAS]
    lineas.append("tipos_institucionales:")
    lineas += [f"  - {tipo}" for tipo in sorted(repository.TIPOS_INSTITUCIONALES)]
    lineas.append("indice_no_publicacion:")
    lineas += [f"  - {_yaml_str(url)}" for url in sorted(repository.INDICE_NO_PUBLICACION)]
    lineas.append("resumen:")
    for clase in ("publico", "institucional", "privado"):
        total = sum(1 for fila in filas if fila["clasificacion"] == clase)
        lineas.append(f"  {clase}: {total}")
    lineas.append(f"  total: {len(filas)}")
    lineas.append("notas_de_juicio:")
    for sujeto, nota in NOTAS_DE_JUICIO:
        lineas.append(f"  - sujeto: {_yaml_str(sujeto)}")
        lineas.append(f"    nota: {_yaml_str(nota)}")
    lineas.append("documentos:")
    for fila in filas:
        lineas.append(f"  - documento_id: {fila['documento_id']}")
        lineas.append(f"    tipo: {fila['tipo']}")
        lineas.append(f"    es_secundaria: {str(fila['es_secundaria']).lower()}")
        lineas.append(f"    clasificacion: {fila['clasificacion']}")
        lineas.append(f"    evidencia: {_yaml_str(str(fila['evidencia']))}")
    return "\n".join(lineas) + "\n"


def generar(corpus_path: Path, corpus_sha: str) -> list[dict[str, object]]:
    """Derive every document's class. Refuses a drifted or dirty checkout first."""
    verify_corpus_pin(corpus_path, corpus_sha)
    expectations = load_expectations()
    if expectations.corpus_sha != corpus_sha:
        raise SystemExit(
            f"corpus_expectations.yaml is pinned to {expectations.corpus_sha} but "
            f"--corpus-sha is {corpus_sha}. Refusing to generate an artifact whose "
            "two halves describe different revisions."
        )

    corpus = load_corpus(corpus_path, expectations)
    filas: list[dict[str, object]] = []
    for doc in corpus.documentos:
        row = repository.documento_row_from_frontmatter(
            corpus_sha, doc.documento_id, doc.frontmatter
        )
        filas.append(
            {
                "documento_id": doc.documento_id,
                "tipo": row["tipo"],
                "es_secundaria": row["es_secundaria"],
                "clasificacion": row["clasificacion"],
                "evidencia": row["clasificacion_evidencia"],
            }
        )
    filas.sort(key=lambda fila: str(fila["documento_id"]))
    return filas


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    filas = generar(args.corpus_path, args.corpus_sha)
    args.output.write_text(render(args.corpus_sha, filas), encoding="utf-8")

    conteos = {
        clase: sum(1 for fila in filas if fila["clasificacion"] == clase)
        for clase in ("publico", "institucional", "privado")
    }
    print(f"{args.output}: {len(filas)} documents — {conteos}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
