-- ============================================================================
-- CLEANUP TEST DATA - Consorcio Canalero Production Database
-- ============================================================================
-- Purpose: Remove E2E/Playwright test data from production database.
-- Generated: 2026-03-25
--
-- Test data patterns targeted:
--   - Emails: *@test.com, *@playwright.com
--   - Names/text: "Playwright", "E2E", "e2e"
--   - CUIT patterns: 20-XXXXXXXX-5 (generated by Date.now() in tests)
--   - Rubro patterns: "rubro-e2e-*"
--
-- SAFETY: NEVER touches admin user jnzader@gmail.com
-- ============================================================================


-- ############################################################################
-- SECTION 1: AUDIT (SELECT counts only — safe to run anytime)
-- ############################################################################

\echo '============================================'
\echo 'SECTION 1: AUDIT — Counting test data rows'
\echo '============================================'

-- ── Users (test-*@playwright.com, *@test.com) ──
\echo ''
\echo '--- users (test accounts) ---'
SELECT COUNT(*) AS test_users
FROM users
WHERE email LIKE '%@playwright.com'
   OR email LIKE '%@test.com'
   AND email != 'jnzader@gmail.com';

-- Show which users would be deleted
SELECT id, email, nombre, apellido, role, created_at
FROM users
WHERE (email LIKE '%@playwright.com' OR email LIKE '%@test.com')
  AND email != 'jnzader@gmail.com'
ORDER BY created_at DESC
LIMIT 20;

-- ── Denuncias historial (child of denuncias — audit log) ──
\echo ''
\echo '--- denuncias_historial (from test denuncias) ---'
SELECT COUNT(*) AS test_denuncias_historial
FROM denuncias_historial dh
JOIN denuncias d ON dh.denuncia_id = d.id
WHERE d.contacto_email LIKE '%@test.com'
   OR d.contacto_email LIKE '%@playwright.com'
   OR d.descripcion ILIKE '%playwright%'
   OR d.descripcion ILIKE '%e2e%';

-- ── Denuncias ──
\echo ''
\echo '--- denuncias (test reports) ---'
SELECT COUNT(*) AS test_denuncias
FROM denuncias
WHERE contacto_email LIKE '%@test.com'
   OR contacto_email LIKE '%@playwright.com'
   OR descripcion ILIKE '%playwright%'
   OR descripcion ILIKE '%e2e%';

-- ── Tramites seguimiento (child of tramites — audit log) ──
\echo ''
\echo '--- tramites_seguimiento (from test tramites) ---'
SELECT COUNT(*) AS test_tramites_seguimiento
FROM tramites_seguimiento ts
JOIN tramites_v2 t ON ts.tramite_id = t.id
WHERE t.titulo ILIKE '%playwright%'
   OR t.titulo ILIKE '%e2e%'
   OR t.descripcion ILIKE '%playwright%'
   OR t.solicitante ILIKE '%playwright%';

-- ── Tramites ──
\echo ''
\echo '--- tramites_v2 (test procedures) ---'
SELECT COUNT(*) AS test_tramites
FROM tramites_v2
WHERE titulo ILIKE '%playwright%'
   OR titulo ILIKE '%e2e%'
   OR descripcion ILIKE '%playwright%'
   OR solicitante ILIKE '%playwright%';

-- ── Mantenimiento logs (child of assets) ──
\echo ''
\echo '--- mantenimiento_logs (from test assets) ---'
SELECT COUNT(*) AS test_mantenimiento_logs
FROM mantenimiento_logs ml
JOIN assets a ON ml.asset_id = a.id
WHERE a.nombre ILIKE '%playwright%'
   OR a.nombre ILIKE '%e2e%'
   OR a.descripcion ILIKE '%playwright%'
   OR ml.descripcion ILIKE '%playwright%'
   OR ml.descripcion ILIKE '%e2e%'
   OR ml.realizado_por ILIKE '%playwright%';

-- ── Assets ──
\echo ''
\echo '--- assets (test infrastructure) ---'
SELECT COUNT(*) AS test_assets
FROM assets
WHERE nombre ILIKE '%playwright%'
   OR nombre ILIKE '%e2e%'
   OR descripcion ILIKE '%playwright%';

-- ── Gastos ──
\echo ''
\echo '--- gastos_v2 (test expenses) ---'
SELECT COUNT(*) AS test_gastos
FROM gastos_v2
WHERE descripcion ILIKE '%playwright%'
   OR descripcion ILIKE '%e2e%';

-- ── Ingresos ──
\echo ''
\echo '--- ingresos_v2 (test income) ---'
SELECT COUNT(*) AS test_ingresos
FROM ingresos_v2
WHERE descripcion ILIKE '%playwright%'
   OR descripcion ILIKE '%e2e%';

-- ── Presupuestos ──
\echo ''
\echo '--- presupuestos_v2 (test budget lines) ---'
SELECT COUNT(*) AS test_presupuestos
FROM presupuestos_v2
WHERE rubro LIKE 'rubro-e2e-%';

-- ── Sugerencias ──
\echo ''
\echo '--- sugerencias_v2 (test suggestions) ---'
SELECT COUNT(*) AS test_sugerencias
FROM sugerencias_v2
WHERE contacto_email LIKE '%@test.com'
   OR contacto_email LIKE '%@playwright.com'
   OR titulo ILIKE '%playwright%'
   OR titulo ILIKE '%e2e%'
   OR contacto_nombre ILIKE '%playwright%'
   OR contacto_nombre ILIKE '%e2e%';

-- ── Capas (tests delete their own, but check for leftovers) ──
\echo ''
\echo '--- capas_v2 (test map layers — leftovers) ---'
SELECT COUNT(*) AS test_capas
FROM capas_v2
WHERE nombre ILIKE '%e2e%'
   OR nombre ILIKE '%playwright%';

\echo ''
\echo '============================================'
\echo 'AUDIT COMPLETE — Review counts above before running Section 2'
\echo '============================================'


-- ############################################################################
-- SECTION 2: CLEANUP (actual DELETEs in a transaction)
-- ############################################################################
-- IMPORTANT: Review Section 1 output FIRST. Then uncomment and run this section.
-- To run: remove the \quit below, or run from the BEGIN line onward.
-- ############################################################################

\echo ''
\echo '!!! STOP HERE — Remove the \\quit below to execute the cleanup !!!'
\quit

BEGIN;

\echo ''
\echo '============================================'
\echo 'SECTION 2: CLEANUP — Deleting test data'
\echo '============================================'

-- ────────────────────────────────────────────────
-- Step 1: Child tables first (FK dependencies)
-- ────────────────────────────────────────────────

-- 1a. denuncias_historial — CASCADE would handle this, but explicit is safer
\echo 'Deleting denuncias_historial for test denuncias...'
DELETE FROM denuncias_historial
WHERE denuncia_id IN (
    SELECT id FROM denuncias
    WHERE contacto_email LIKE '%@test.com'
       OR contacto_email LIKE '%@playwright.com'
       OR descripcion ILIKE '%playwright%'
       OR descripcion ILIKE '%e2e%'
);

-- 1b. tramites_seguimiento — child of tramites_v2
\echo 'Deleting tramites_seguimiento for test tramites...'
DELETE FROM tramites_seguimiento
WHERE tramite_id IN (
    SELECT id FROM tramites_v2
    WHERE titulo ILIKE '%playwright%'
       OR titulo ILIKE '%e2e%'
       OR descripcion ILIKE '%playwright%'
       OR solicitante ILIKE '%playwright%'
);

-- 1c. mantenimiento_logs — child of assets
\echo 'Deleting mantenimiento_logs for test assets...'
DELETE FROM mantenimiento_logs
WHERE asset_id IN (
    SELECT id FROM assets
    WHERE nombre ILIKE '%playwright%'
       OR nombre ILIKE '%e2e%'
       OR descripcion ILIKE '%playwright%'
);
-- Also delete orphan maintenance logs that match test patterns directly
DELETE FROM mantenimiento_logs
WHERE descripcion ILIKE '%playwright%'
   OR descripcion ILIKE '%e2e%'
   OR realizado_por ILIKE '%playwright%';

-- ────────────────────────────────────────────────
-- Step 2: Parent tables (domain entities)
-- ────────────────────────────────────────────────

-- 2a. denuncias
\echo 'Deleting test denuncias...'
DELETE FROM denuncias
WHERE contacto_email LIKE '%@test.com'
   OR contacto_email LIKE '%@playwright.com'
   OR descripcion ILIKE '%playwright%'
   OR descripcion ILIKE '%e2e%';

-- 2b. tramites_v2
\echo 'Deleting test tramites...'
DELETE FROM tramites_v2
WHERE titulo ILIKE '%playwright%'
   OR titulo ILIKE '%e2e%'
   OR descripcion ILIKE '%playwright%'
   OR solicitante ILIKE '%playwright%';

-- 2c. assets
\echo 'Deleting test assets...'
DELETE FROM assets
WHERE nombre ILIKE '%playwright%'
   OR nombre ILIKE '%e2e%'
   OR descripcion ILIKE '%playwright%';

-- 2d. gastos_v2
\echo 'Deleting test gastos...'
DELETE FROM gastos_v2
WHERE descripcion ILIKE '%playwright%'
   OR descripcion ILIKE '%e2e%';

-- 2e. ingresos_v2
\echo 'Deleting test ingresos...'
DELETE FROM ingresos_v2
WHERE descripcion ILIKE '%playwright%'
   OR descripcion ILIKE '%e2e%';

-- 2f. presupuestos_v2
\echo 'Deleting test presupuestos...'
DELETE FROM presupuestos_v2
WHERE rubro LIKE 'rubro-e2e-%';

-- 2g. sugerencias_v2
\echo 'Deleting test sugerencias...'
DELETE FROM sugerencias_v2
WHERE contacto_email LIKE '%@test.com'
   OR contacto_email LIKE '%@playwright.com'
   OR titulo ILIKE '%playwright%'
   OR titulo ILIKE '%e2e%'
   OR contacto_nombre ILIKE '%playwright%'
   OR contacto_nombre ILIKE '%e2e%';

-- 2h. capas_v2 (leftover test layers)
\echo 'Deleting leftover test capas...'
DELETE FROM capas_v2
WHERE nombre ILIKE '%e2e%'
   OR nombre ILIKE '%playwright%';

-- ────────────────────────────────────────────────
-- Step 3: Users last (many tables FK to users)
-- ────────────────────────────────────────────────

-- SAFETY: Explicitly exclude admin
\echo 'Deleting test user accounts (NEVER jnzader@gmail.com)...'
DELETE FROM users
WHERE (email LIKE '%@playwright.com' OR email LIKE '%@test.com')
  AND email != 'jnzader@gmail.com';

\echo ''
\echo '============================================'
\echo 'CLEANUP COMPLETE — Committing transaction'
\echo '============================================'

COMMIT;
